Customize binary-builder pipeline for SUSE CF process
SUSE/cf-buildpacks-ci pull request #2
Opened 2017-04-17 17:57 UTC by alexjh

2017-04-19 17:10 UTC, mook-as requested changes
Mostly removing references to `jandubois`. (I didn't point out all instances)

Can we deploy this to the local concourse so we can tell it's working-ish? :D

2017-04-19 17:10 UTC, mook-as commented on lib/buildpacks-ci-pipeline-update-command.rb
> +      --load-vars-from=private.yml \
How about `--load-vars-from=<(blackbox_cat private.yml)`? That should hopefully eliminate the temporary file on disk…

2017-04-19 17:10 UTC, mook-as commented on pipelines/binary-builder.yml
> +      repository: jandubois/opensusefs2
I think we want `SUSE/cf-suse-stacks` instead

2017-04-19 17:10 UTC, mook-as commented on pipelines/binary-builder.yml
> +<% %w(bower composer glide godep nginx node yarn).each do |auto_dep| %>
I'm getting the feeling this list should have been refactored to somewhere else at the top of this file

2017-04-19 17:10 UTC, mook-as commented on public-config.yml
> +buildpacks-ci-pipeline-uri: http://concourse.suse.de/teams/main/pipelines/cf-buildpacks-ci
Ah, we're using that concourse (instead of the office-local one)? I guess it makes sense (since that has wider visibility)?

2017-04-19 17:10 UTC, mook-as commented on tasks/build-binary/task.yml
> +    repository: jandubois/opensusefs2
s/jandubois/SUSE/g

2017-04-19 17:10 UTC, mook-as commented on tasks/run-binary-builder-integration-specs/run.sh
> +    sudo zypper refresh && sudo zypper install -y aws-cli
`zypper install` will automatically refresh, unless you say `zypper --no-refresh install`.

2017-04-20 17:38 UTC, alexjh commented on tasks/run-binary-builder-integration-specs/run.sh
> +    sudo zypper refresh && sudo zypper install -y aws-cli
Fixed in 6ba9b52742b066a5450beb28ac9563c4cb09e7bc

2017-04-20 17:39 UTC, alexjh commented on public-config.yml
> +buildpacks-ci-pipeline-uri: http://concourse.suse.de/teams/main/pipelines/cf-buildpacks-ci
I thought that makes a reasonable default. It doesn't have an effect for this task, this will be used for the unit tests of the CI pipeline.

2017-04-20 17:46 UTC, alexjh commented on lib/buildpacks-ci-pipeline-update-command.rb
> +      --load-vars-from=private.yml \
Oh, this is awesome. If you have the decrypted file on disk, it uses that, so you can experiment without encrypting and committing multiple times.

Fixed in c528b1d4ed230259c6086b24fcac06d2f4be7d5b

2017-04-20 18:32 UTC, alexjh commented on pipelines/binary-builder.yml
> +      repository: jandubois/opensusefs2
Done with d3711b52331d8a5bb9636f6adaf8f7a8d2e16947, although I'm leaving the pipeline deployed to `concourse.van` using `jandubois/opensusefs2` until the official one is ready.

2017-04-20 18:32 UTC, alexjh commented on tasks/build-binary/task.yml
> +    repository: jandubois/opensusefs2
Done.

2017-04-21 18:18 UTC, alexjh commented on pipelines/binary-builder.yml
> +<% %w(bower composer glide godep nginx node yarn).each do |auto_dep| %>
Fixed in 089f52e

2017-04-21 23:06 UTC, mook-as approved these changes
LGTM, waiting for a build on our concourse before merging. (Is that using your minio, still? Should probably do it with the minio colocated with the concourse box)

2017-04-25 16:34 UTC, alexjh commented
Ok, finally got it working with minio.van:
http://concourse.van:9000/minio/pivotal-buildpacks/dependencies/

Concourse didn't like me changing the S3 endpoint, it kept the old one cached and didn't realize it needed to build again. The only way I could get it to rebuild was to delete the pipeline and run it all again.

2017-05-16 17:05 UTC, alexjh commented
Too many changes since I originally made this branch, I'm going to close this PR and make a new one with the new blackbox credentials, etc.

2017-05-16 17:05 UTC, closed without merging